# Configuration file for Sir Doom Turtle`s Elytra Rebalance

# This multiplier affects the speed of the Elytra.
# Setting this to 1.0 will use the default speed without modification.
# Accepted values from 0.0 to 1.0
# Vanilla Minecraft Default is 1.0
elytra_speed_modifier = 0.75

# This value sets the custom durability of the Elytra.
# Accepted values from 1 to 9999
# Vanilla Minecraft Default is 432
elytra_durability = 800
